/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/ui/buttons/ActionButton.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    CardComponent: typeof import('./src/components/ui/dashboard/CardComponent.vue')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmationModalComponent: typeof import('./src/components/ui/confirmationModal/ConfirmationModalComponent.vue')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    ErrorMessageComponent: typeof import('./src/components/ui/error/ErrorMessageComponent.vue')['default']
    IconCommunity: typeof import('./src/components/ui/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/ui/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/ui/icons/IconEcosystem.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    IconSupport: typeof import('./src/components/ui/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/ui/icons/IconTooling.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItemListComponent: typeof import('./src/components/ui/layout/navbar/ItemListComponent.vue')['default']
    LoadingComponent: typeof import('./src/components/ui/layout/LoadingComponent.vue')['default']
    MainComponent: typeof import('./src/components/ui/layout/MainComponent.vue')['default']
    NavComponent: typeof import('./src/components/ui/layout/NavComponent.vue')['default']
    NumberInputComponent: typeof import('./src/components/ui/input/NumberInputComponent.vue')['default']
    PaginationComponent: typeof import('./src/components/ui/pagination/PaginationComponent.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    ProfileDropdownComponent: typeof import('./src/components/ui/layout/navbar/ProfileDropdownComponent.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchComponent: typeof import('./src/components/ui/search/SearchComponent.vue')['default']
    StatusLabelComponent: typeof import('./src/components/ui/schedule/StatusLabelComponent.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TableComponent: typeof import('./src/components/ui/tables/TableComponent.vue')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TextInputComponent: typeof import('./src/components/ui/input/TextInputComponent.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
